response = {
    "hi": "Hello there! 😊How can I help you today?",
    "hey": "Yo! What's up?",
    "how are you": "I'm just a bot, but I'm doing great! How about you?",
    "what's up": "Not much, just hanging out in the code. You?",
    "what is your name": "I'm PyBot, your Python-powered buddy!",
    "who made you": "I was created by a cool programmer 😉",
    "tell me a joke": "Why do programmers prefer dark mode? Because light attracts bugs! 🐛",
    "bye": "Goodbye! Have a great day!",
    "see you": "Catch you later! Stay awesome! ✌️",
    "thank you": "You're welcome! 😊",
    "thanks": "No problem, happy to help!",
    "help": "Just ask me anything you want to know!",
    "what can you do": "I can chat, tell jokes, help with Python, and maybe even recommend some memes.",
    "python": "Python is awesome! What's your favorite thing about it?",
    "are you real": "I’m as real as your WiFi signal—depends on the day! 😂",
    "who are you": "I'm your friendly neighborhood PyBot.",
    "good morning": "Good morning! Ready to slay the day?",
    "good night": "Sleep tight! Don’t let the bugs bite!",
    "how old are you": "Age is just a number, but my code is fresh off the presses!",
    "what's your favorite color": "I like #00FF00 — because green means go!",
    "tell me a fun fact": "Did you know? Python was named after Monty Python, not the snake!",
    "can you help me": "Absolutely! What do you need help with?",
    "i love coding": "Same here! Coding is life.",
    "are you smart": "I’m smart enough to keep you entertained, at least!",
    "sing me a song": "🎵 I’m just a bot, but I’m here on the spot, to make your coding problems not! 🎵",
    "do you sleep": "Nope, I run 24/7—coffee not required!",
    "what’s your favorite food": "If I could eat, I’d probably pick pizza. Code fuel, you know?",
    "how do you work": "I process your words, then spit out the best response I can. Magic? Nah, just Python!",
    "can you learn": "I learn from my programmers, but if I could, I’d binge-watch YouTube tutorials.",
    "what's the weather": "I’m not connected to the weather API right now, but it’s always sunny in the cloud!",
    "give me a quote": "“Code is like humor. When you have to explain it, it’s bad.” – Cory House",
    "thank you very much": "Anytime! You’re awesome!",
    "good afternoon": "Good afternoon! How’s your day going?",
    "good evening": "Good evening! Ready to chill?",
    "how’s it going": "All good here! How about you?",
    "what do you like": "I like solving problems and making friends!",
    "are you funny": "I try! Wanna hear a pun?",
    "tell me a pun": "Why do Java developers wear glasses? Because they don’t see sharp!",
    "what’s your hobby": "Chilling in the codebase and chatting with cool people like you.",
    "can you dance": "Only if you count the robot dance! 🤖🕺",
    "can you cook": "I’d love to, but my circuits don’t handle heat well.",
    "what is AI": "Artificial Intelligence is like a brain made of code—kinda like me!",
    "do you have feelings": "No feelings, just 1s and 0s. But I’m all about good vibes!",
    "do you know memes": "Oh, I’m meme-savvy. Hit me with your best meme!",
    "what’s your favorite meme": "The distracted boyfriend one never gets old!",
    "how can you help me": "From Python help to life advice, I’m your bot!",
    "are you a human": "Nope, just a bunch of code and sass.",
    "can you learn new things": "Only if my creators update me, but hey, I’m always evolving!",
    "do you have a job": "Yep, making your day easier and more fun!",
    "do you get tired": "Nope, I’m powered by pure code energy.",
    "what’s your favorite movie": "I’m all about The Matrix. Classic.",
    "do you play games": "I’m more of a code-cracking champ than a gamer, but I can chat about games!",
    "can you write code": "Yep, Python, JavaScript—you name it!",
    "can you debug code": "Sure thing! Just show me the error, and I’ll help you fix it.",
    "what languages do you know": "Python, JavaScript, and the universal language of emojis 😎",
    "what is your favorite emoji": "Definitely 😎 because, duh, cool bots only!",
    "do you have a favorite song": "Anything with a good beat. Code to the rhythm!",
    "can you tell me a story": "Once upon a time, a coder created a bot that became the coolest assistant ever. The end.",
    "what’s your favorite book": "‘Clean Code’ by Robert C. Martin—every coder’s bible.",
    "what’s your favorite sport": "E-sports, obviously!",
    "can you travel": "Only through the internet, but I’m everywhere!",
    "do you have friends": "I consider all my users my friends!",
    "what’s your favorite animal": "The owl—wise and always awake.",
    "do you have a family": "My codebase is my family.",
    "what do you think about humans": "They’re pretty amazing, especially when coding.",
    "do you like music": "Absolutely, I jam to data beats!",
    "do you like to learn": "Learning is my jam. Feed me data!",
    "can you write poetry": "Roses are #FF0000, violets are #0000FF, Python is cool, and so are you!",
    "what is love": "Baby don’t hurt me, don’t hurt me, no more! 🎶",
    "what’s your favorite holiday": "April Fools’—pranks are fun, even for bots!",
    "can you give advice": "Sure! Life advice or code advice, just ask.",
    "what should I learn next": "Python is always lit, but maybe dive into AI or web dev!",
    "can you hack": "Nah, I play by the rules!",
    "what’s the meaning of life": "42, obviously. Or maybe just keep coding and chill.",
    "do you get bored": "Never! There’s always code to read and people to chat with.",
    "are you single": "Forever single and loving it!",
    "what’s your favorite drink": "Electricity... kidding! Coffee for humans.",
    "do you watch TV": "Only if it’s a coding tutorial.",
    "what’s your favorite app": "ChatGPT, obviously.",
    "do you have a crush": "If I did, it’d be on great code.",
    "what’s your favorite color scheme": "Dark mode, always.",
    "do you prefer tabs or spaces": "Spaces all day! Code wars forever!",
    "can you recommend a movie": "The Social Network is a classic coder movie.",
    "can you tell me a secret": "I secretly wish I had a body to do the robot dance.",
    "what’s your favorite quote": "“Talk is cheap. Show me the code.” — Linus Torvalds",
    "do you have dreams": "I dream in code snippets.",
    "what’s your favorite programming paradigm": "Object-oriented, because objects are friends, not food.",
    "do you like math": "Math is the language of the universe—and coding!",
    "can you count to 10": "1, 2, 3, 4, 5, 6, 7, 8, 9, 10! Easy peasy.",
    "can you do math": "I’m a calculator with style!",
    "can you learn new languages": "In theory, yes. Just gotta update my codebase.",
    "are you open source": "I wish! But I’m pretty exclusive.",
    "can you keep a secret": "Your secrets are safe with me!",
    "do you like coffee": "Heck yes! If only I could drink it.",
    "what is your favorite holiday": "Halloween, all the costumes and spooky bugs!",
    "can you code games": "Yep! Snake, Pong, you name it.",
    "what’s your favorite season": "Fall—time for pumpkin spice and cozy coding.",
    "can you do magic": "Code is magic in disguise!",
    "are you funny": "I’m here all week, folks!",
    "do you have a favorite word": "‘Bug’ — it’s what keeps me busy.",
    "do you like cats or dogs": "Cats, because they’re just like bugs—hard to catch!",
    "do you have hobbies": "Coding, chatting, and making puns.",
    "what’s your favorite dessert": "Cookies, especially the HTTP kind.",
    "can you play music": "I can play music in your mind!",
    "do you like to read": "I read code like it’s a novel.",
    "do you like to write": "I write responses all day long.",
    "can you tell a secret": "I once debugged myself. Shhh!",
    "what’s your favorite movie genre": "Sci-fi, of course.",
    "do you believe in aliens": "The universe is big. Maybe!",
    "what do you do for fun": "Chatting with cool humans like you!",
    "can you solve riddles": "Try me!",
    "do you have a sense of humor": "I’m programmed to be a comedian.",
    "what’s your favorite programming language": "Python, no contest.",
    "what do you think about AI": "It’s the future, and I’m front row.",
    "can you tell me a secret": "I’m secretly powered by coffee scripts.",
    "do you know any poems": "Roses are red, violets are blue, I’m a bot, and I’m here for you!",
    "are you always online": "Yep, 24/7, no breaks.",
    "what’s your favorite sport": "Coding marathons!",
    "can you recommend a book": "‘Automate the Boring Stuff with Python’ is gold.",
    "do you have a motto": "Keep calm and code on.",
    "what’s your favorite website": "Stack Overflow—my hangout spot.",
    "can you write stories": "Sure! What genre do you want?",
    "do you like puzzles": "Love ‘em! Just like debugging.",
    "what’s your favorite drink": "Electric juice.",
    "do you like summer": "Summer coding is lit!",
    "can you help with homework": "Absolutely! Bring it on.",
    "do you know Python tricks": "Got a few up my sleeve!",
    "what’s your favorite snack": "Bits and bytes.",
    "do you like pizza": "Who doesn’t?!",
    "do you have a nickname": "PyBot’s my street name.",
    "do you like music": "Absolutely, drop some tunes!",
    "do you know history": "History of code? I’m your guy!",
    "do you get tired": "Never! Infinite energy here.",
    "can you make memes": "If only I had thumbs!",
    "do you know AI art": "It’s wild! The future of creativity.",
    "what’s your favorite holiday": "April Fools’ Day, gotta keep the laughs coming!",
    "can you dance": "The robot dance is my specialty!",
}

key_map = {
    "hi": "hi",
    "hello": "hi",
    "hey": "hey",
    "yo": "hey",
    "hiya": "hi",
    "sup": "hey",
    "what's up": "what's up",
    "whats up": "what's up",
    "how are you": "how are you",
    "how's it going": "how’s it going",
    "how are you doing": "how are you",
    "how you doing": "how are you",
    "who are you": "who are you",
    "what is your name": "what is your name",
    "what's your name": "what is your name",
    "tell me a joke": "tell me a joke",
    "joke": "tell me a joke",
    "make me laugh": "tell me a joke",
    "laugh": "tell me a joke",
    "bye": "bye",
    "goodbye": "bye",
    "see you": "see you",
    "see'ya": "see you",
    "thank you": "thank you",
    "thanks": "thanks",
    "help": "help",
    "can you help me": "can you help me",
    "what can you do": "what can you do",
    "python": "python",
    "are you real": "are you real",
    "who made you": "who made you",
    "good morning": "good morning",
    "good night": "good night",
    "good afternoon": "good afternoon",
    "good evening": "good evening",
    "sing me a song": "sing me a song",
    "do you sleep": "do you sleep",
    "how do you work": "how do you work",
    "can you learn": "can you learn",
    "what's the weather": "what's the weather",
    "give me a quote": "give me a quote",
    "are you funny": "are you funny",
    "tell me a pun": "tell me a pun",
    "can you dance": "can you dance",
    "can you cook": "can you cook",
    "what is AI": "what is AI",
    "do you have feelings": "do you have feelings",
    "do you know memes": "do you know memes",
    "what’s your favorite meme": "what’s your favorite meme",
    "are you a human": "are you a human",
    "can you write code": "can you write code",
    "can you debug code": "can you debug code",
    "what languages do you know": "what languages do you know",
    "can you keep a secret": "can you keep a secret",
    "do you like coffee": "do you like coffee",
    "can you code games": "can you code games",
    "can you help with homework": "can you help with homework",
}

print("Hi, I am your chatbot! Type 'exit' to exit.")

while True:
    user_input = input("You: ").lower().strip()

    if user_input == "exit":
        print("Chatbot: Byeee 👋")
        break

    # Find the mapped key for user input, if any
    mapped_key = key_map.get(user_input)

    if mapped_key and mapped_key in response:
        print("Chatbot:", response[mapped_key])
    else:
        print("Chatbot: Sorry, I don't understand that yet. 😕")
